FROM docker.1ms.run/oven/bun:1 AS builder

WORKDIR /app

COPY . .

RUN bun install --frozen-lockfile
RUN bun run --filter @workspace/frontend build

FROM docker.1ms.run/caddy:2-alpine AS runtime

COPY Caddyfile.frontend /etc/caddy/Caddyfile
COPY --from=builder /app/dist/frontend /usr/share/caddy

EXPOSE 80
