FROM docker.1ms.run/oven/bun:1-slim AS runtime

RUN apt-get update && apt-get install -y docker-cli

WORKDIR /app

COPY dist/backend/server.js ./server.js

ENV PORT=3000
EXPOSE 3000

CMD ["bun", "server.js"]
